# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-20 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0002_indicador_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='descripcion_corta',
            field=models.CharField(blank=True, default=b'', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='limite_inferior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='limite_inferior_semi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='limite_semi_superior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='limite_superior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='metodo',
            field=models.CharField(blank=True, default=b'', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='descripcion',
            field=models.CharField(max_length=1500),
        ),
    ]
