# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-12 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0003_auto_20170620_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='static_img',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
