# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-12 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0004_ciudad_static_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='href',
            field=models.CharField(default=b'', max_length=40),
        ),
    ]
