# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-03 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0006_indicador_activado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='ciudad_padre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciudad.Ciudad'),
        ),
    ]
