# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-03 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0007_ciudad_ciudad_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='activado',
            field=models.BooleanField(default=True),
        ),
    ]
