# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0008_auto_20160107_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='url',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='variable',
            field=models.CharField(max_length=100),
        ),
    ]
