# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0010_ciudad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='clima',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='url',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
